const dummyData2 = [
  {
    id: 1,
    name: 'Morris MR-1023',
    image: 'https://your-image-path/ABR-55-OSE-201-BEIGE.jpg',
    price: 1012000,
    availability: true,
    size: '10x14',
    color: 'Gray / Teal / Green',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'In Stock'],
    description: 'Morris – Code: ABR-55-OSE-201-BEIGE',
    customisable: false,
  },
  {
    id: 2,
    name: 'Morris MR-1024',
    image: 'https://your-image-path/ABR-55-OSE-201-CAMEL.JPG',
    price: 780000,
    availability: true,
    size: '9x12',
    color: 'Gray / Brown',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'In Stock'],
    description: 'Morris – Code: ABR-55-OSE-201-CAMEL',
    customisable: false,
  },
  {
    id: 3,
    name: 'Morris MR-1025',
    image: 'https://your-image-path/ABR-55-OSE-203-CAMEL.jpg',
    price: 1300000,
    availability: true,
    size: '12x15',
    color: 'Gray / Blue',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'In Stock'],
    description: 'Morris – Code: ABR-55-OSE-203-CAMEL',
    customisable: false,
  },
  {
    id: 4,
    name: 'Morris MR-1026',
    image: 'https://your-image-path/ABR-55-OSE-204-BEIGE.jpg',
    price: 780000,
    availability: true,
    size: '9x12 / 10x14',
    color: 'Gray / Orange / Teal',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'In Stock'],
    description: 'Morris – Code: ABR-55-OSE-204-BEIGE',
    customisable: false,
  },
  {
    id: 5,
    name: 'Morris MR-1027',
    image: 'https://your-image-path/ABR-55-OSE-204-BROWN-BROWN.jpg',
    price: 780000,
    availability: true,
    size: '9x12',
    color: 'Brown / Green',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'In Stock'],
    description: 'Morris – Code: ABR-55-OSE-204-BROWN-BROWN',
    customisable: false,
  },
  {
    id: 6,
    name: 'Morris MR-1028',
    image: 'https://your-image-path/ABR-55-OSE-205-CAMEL.jpg',
    price: 780000,
    availability: true,
    size: '9x12 / 10x14 / 12x15',
    color: 'Gray / Teal / Green',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'In Stock'],
    description: 'Morris – Code: ABR-55-OSE-205-CAMEL',
    customisable: false,
  },
  {
    id: 7,
    name: 'Morris MR-1029',
    image: 'https://your-image-path/ABR-55-OSE-211-CHARCOAL.jpg',
    price: 578000,
    availability: true,
    size: '8x10 / 9x12 / 10x14',
    color: 'Black / Green / Pink',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'In Stock'],
    description: 'Morris – Code: ABR-55-OSE-211-CHARCOAL',
    customisable: false,
  },
  {
    id: 8,
    name: 'Morris MR-1030',
    image: 'https://your-image-path/MR-1030-MEADOW.jpg',
    price: 0,
    availability: true,
    size: 'Custom',
    color: 'Green / Pink / Ivory',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'Customisable'],
    description: 'Morris – Code: MR-1030-MEADOW',
    customisable: true,
  },
  {
    id: 9,
    name: 'Morris MR-1031',
    image: 'https://your-image-path/MR-1031-FLORA.jpg',
    price: 0,
    availability: true,
    size: 'Custom',
    color: 'Gray / Gold / Rust',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'Customisable'],
    description: 'Morris – Code: MR-1031-FLORA',
    customisable: true,
  },
  {
    id: 10,
    name: 'Morris MR-1032',
    image: 'https://your-image-path/MR-1032-PINE.jpg',
    price: 0,
    availability: true,
    size: 'Custom',
    color: 'Brown / Rust / Gold',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'Customisable'],
    description: 'Morris – Code: MR-1032-PINE',
    customisable: true,
  },
  {
    id: 11,
    name: 'Morris MR-1033',
    image: 'https://your-image-path/MR-1033-MARY.jpg',
    price: 0,
    availability: true,
    size: 'Custom',
    color: 'Beige / Gold / Red',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'Customisable'],
    description: 'Morris – Code: MR-1033-MARY',
    customisable: true,
  },
  {
    id: 12,
    name: 'Morris MR-1034',
    image: 'https://your-image-path/MR-1034-GARDENIA.jpg',
    price: 0,
    availability: true,
    size: 'Custom',
    color: 'Blue / Multi / Orange',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'Customisable'],
    description: 'Morris – Code: MR-1034-GARDENIA',
    customisable: true,
  },
  {
    id: 13,
    name: 'Morris MR-1035',
    image: 'https://your-image-path/MR-1035-EMBER.jpg',
    price: 0,
    availability: true,
    size: 'Custom',
    color: 'Blue / Red / Green',
    material: 'Pure Silk & Wool',
    style: 'Transitional',
    pileHeight: 'Medium',
    collection: 'Morris',
    characteristics: ['Handknotted', 'Rectangular', 'Customisable'],
    description: 'Morris – Code: MR-1035-EMBER',
    customisable: true,
  },
];
const dummyData = [
  {
    id: 1,
    name: 'Acadia Wool Rug 3x5',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1375,
    availability: true,
    size: '3x5',
    color: 'Blue',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Acadia',
    characteristics: ['Hand Crafted', 'Indoor', 'Easy Care'],
    description: 'Acadia – Code: ACA-01',
    customisable: true,
  },
  {
    id: 2,
    name: 'Aakar Cotton Rug 2x3',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 875,
    availability: true,
    size: '2x3',
    color: 'Red',
    material: 'Cotton',
    style: 'Solid',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Easy Care', 'Indoor'],
    description: 'Aakar – Code: AAK-02',
    customisable: false,
  },
  {
    id: 3,
    name: 'Adair Polyester Rug 5x8',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2599,
    availability: false,
    size: '5x8',
    color: 'Gray',
    material: 'Polyester',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Adair',
    characteristics: ['Pet Friendly', 'Outdoor'],
    description: 'Adair – Code: ADA-03',
    customisable: true,
  },
  {
    id: 4,
    name: 'Aibel Wool Rug 6x9',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 3299,
    availability: true,
    size: '6x9',
    color: 'Multicolor',
    material: 'Wool',
    style: 'Botanical',
    pileHeight: 'High-Low',
    collection: 'Aibel',
    characteristics: ['Natural Fiber', 'Hand Crafted', 'Indoor'],
    description: 'Aibel – Code: AIB-04',
    customisable: false,
  },
  {
    id: 5,
    name: 'Aion Linen Rug 4x6',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1150,
    availability: true,
    size: '4x6',
    color: 'Pink',
    material: 'Linen',
    style: 'Vintage',
    pileHeight: 'Low',
    collection: 'Aion',
    characteristics: ['Indoor', 'Easy Care'],
    description: 'Aion – Code: AIO-05',
    customisable: false,
  },
  {
    id: 6,
    name: 'Acadia Rayon Rug 8x10',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 3480,
    availability: true,
    size: '8x10',
    color: 'Green',
    material: 'Rayon',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Acadia',
    characteristics: ['Pet Friendly', 'Easy Care', 'Indoor'],
    description: 'Acadia – Code: ACA-06',
    customisable: true,
  },
  {
    id: 7,
    name: 'Adair Polyester Rug Square',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1950,
    availability: false,
    size: 'Square',
    color: 'Gray',
    material: 'Polyester',
    style: 'Geometry',
    pileHeight: 'Medium',
    collection: 'Adair',
    characteristics: ['Outdoor', 'Easy Care'],
    description: 'Adair – Code: ADA-07',
    customisable: false,
  },
  {
    id: 8,
    name: 'Aakar Cotton Rug Oval',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 699,
    availability: true,
    size: 'Oval',
    color: 'Black',
    material: 'Cotton',
    style: 'Lines',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Hand Crafted', 'Indoor'],
    description: 'Aakar – Code: AAK-08',
    customisable: false,
  },
  {
    id: 9,
    name: 'Aibel Wool Rug 2x3',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 425,
    availability: false,
    size: '2x3',
    color: 'Red',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Aibel',
    characteristics: ['Easy Care', 'Natural Fiber'],
    description: 'Aibel – Code: AIB-09',
    customisable: false,
  },
  {
    id: 10,
    name: 'Aion Polyester Rug 5x8',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2150,
    availability: true,
    size: '5x8',
    color: 'Gray',
    material: 'Polyester',
    style: 'Solid',
    pileHeight: 'High',
    collection: 'Aion',
    characteristics: ['Indoor', 'Pet Friendly'],
    description: 'Aion – Code: AIO-10',
    customisable: true,
  },
  {
    id: 11,
    name: 'Acadia Wool Rug 4x6',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1490,
    availability: true,
    size: '4x6',
    color: 'Green',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Acadia',
    characteristics: ['Indoor', 'Easy Care', 'Hand Crafted'],
    description: 'Acadia – Code: ACA-11',
    customisable: false,
  },
  {
    id: 12,
    name: 'Aakar Cotton Rug 3x5',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 999,
    availability: true,
    size: '3x5',
    color: 'Blue',
    material: 'Cotton',
    style: 'Lines',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Easy Care', 'Indoor'],
    description: 'Aakar – Code: AAK-12',
    customisable: false,
  },
  {
    id: 13,
    name: 'Adair Rayon Rug 6x9',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2699,
    availability: false,
    size: '6x9',
    color: 'Gray',
    material: 'Rayon',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Adair',
    characteristics: ['Pet Friendly', 'Outdoor'],
    description: 'Adair – Code: ADA-13',
    customisable: false,
  },
  {
    id: 14,
    name: 'Aibel Wool Rug 8x10',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 3250,
    availability: true,
    size: '8x10',
    color: 'Black',
    material: 'Wool',
    style: 'Solid',
    pileHeight: 'High-Low',
    collection: 'Aibel',
    characteristics: ['Indoor', 'Hand Crafted', 'Natural Fiber'],
    description: 'Aibel – Code: AIB-14',
    customisable: false,
  },
  {
    id: 15,
    name: 'Aion Linen Rug 5x8',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1350,
    availability: true,
    size: '5x8',
    color: 'Pink',
    material: 'Linen',
    style: 'Vintage',
    pileHeight: 'Low',
    collection: 'Aion',
    characteristics: ['Easy Care', 'Indoor'],
    description: 'Aion – Code: AIO-15',
    customisable: false,
  },
  {
    id: 16,
    name: 'Acadia Polyester Rug 3x5',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1750,
    availability: false,
    size: '3x5',
    color: 'Gray',
    material: 'Polyester',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Acadia',
    characteristics: ['Pet Friendly', 'Indoor'],
    description: 'Acadia – Code: ACA-16',
    customisable: false,
  },
  {
    id: 17,
    name: 'Aakar Cotton Rug 2x3',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 599,
    availability: true,
    size: '2x3',
    color: 'Red',
    material: 'Cotton',
    style: 'Solid',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Indoor', 'Hand Crafted'],
    description: 'Aakar – Code: AAK-17',
    customisable: false,
  },
  {
    id: 18,
    name: 'Adair Wool Rug 5x8',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2099,
    availability: true,
    size: '5x8',
    color: 'Gray',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Adair',
    characteristics: ['Indoor', 'Natural Fiber'],
    description: 'Adair – Code: ADA-18',
    customisable: false,
  },
  {
    id: 19,
    name: 'Aibel Wool Rug Oval',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2899,
    availability: true,
    size: 'Oval',
    color: 'Multicolor',
    material: 'Wool',
    style: 'Botanical',
    pileHeight: 'High-Low',
    collection: 'Aibel',
    characteristics: ['Natural Fiber', 'Hand Crafted'],
    description: 'Aibel – Code: AIB-19',
    customisable: true,
  },
  {
    id: 20,
    name: 'Aion Polyester Rug 6x9',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2650,
    availability: false,
    size: '6x9',
    color: 'Gray',
    material: 'Polyester',
    style: 'Geometry',
    pileHeight: 'Medium',
    collection: 'Aion',
    characteristics: ['Easy Care', 'Outdoor'],
    description: 'Aion – Code: AIO-20',
    customisable: false,
  },
  {
    id: 21,
    name: 'Acadia Wool Rug 5x8',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1899,
    availability: true,
    size: '5x8',
    color: 'Blue',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Acadia',
    characteristics: ['Hand Crafted', 'Indoor'],
    description: 'Acadia – Code: ACA-21',
    customisable: false,
  },
  {
    id: 22,
    name: 'Aakar Cotton Rug 4x6',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1199,
    availability: true,
    size: '4x6',
    color: 'Pink',
    material: 'Cotton',
    style: 'Solid',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Easy Care', 'Indoor'],
    description: 'Aakar – Code: AAK-22',
    customisable: false,
  },
  {
    id: 23,
    name: 'Adair Polyester Rug 8x10',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 3100,
    availability: false,
    size: '8x10',
    color: 'Gray',
    material: 'Polyester',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Adair',
    characteristics: ['Pet Friendly', 'Outdoor'],
    description: 'Adair – Code: ADA-23',
    customisable: false,
  },
  {
    id: 24,
    name: 'Aibel Rayon Rug 3x5',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 850,
    availability: true,
    size: '3x5',
    color: 'Red',
    material: 'Rayon',
    style: 'Geometry',
    pileHeight: 'Medium',
    collection: 'Aibel',
    characteristics: ['Indoor', 'Easy Care'],
    description: 'Aibel – Code: AIB-24',
    customisable: false,
  },
  {
    id: 25,
    name: 'Aion Linen Rug 6x9',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1850,
    availability: true,
    size: '6x9',
    color: 'Green',
    material: 'Linen',
    style: 'Vintage',
    pileHeight: 'Low',
    collection: 'Aion',
    characteristics: ['Indoor', 'Hand Crafted'],
    description: 'Aion – Code: AIO-25',
    customisable: false,
  },
  {
    id: 26,
    name: 'Acadia Polyester Rug Oval',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2050,
    availability: true,
    size: 'Oval',
    color: 'Multicolor',
    material: 'Polyester',
    style: 'Botanical',
    pileHeight: 'High-Low',
    collection: 'Acadia',
    characteristics: ['Natural Fiber', 'Indoor', 'Easy Care'],
    description: 'Acadia – Code: ACA-26',
    customisable: true,
  },
  {
    id: 27,
    name: 'Aakar Cotton Rug Square',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 799,
    availability: false,
    size: 'Square',
    color: 'Black',
    material: 'Cotton',
    style: 'Lines',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Indoor', 'Hand Crafted'],
    description: 'Aakar – Code: AAK-27',
    customisable: false,
  },
  {
    id: 28,
    name: 'Adair Wool Rug 2x3',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 499,
    availability: true,
    size: '2x3',
    color: 'Gray',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Adair',
    characteristics: ['Easy Care', 'Indoor'],
    description: 'Adair – Code: ADA-28',
    customisable: false,
  },
  {
    id: 29,
    name: 'Aibel Wool Rug 4x6',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1499,
    availability: true,
    size: '4x6',
    color: 'Red',
    material: 'Wool',
    style: 'Geometry',
    pileHeight: 'Medium',
    collection: 'Aibel',
    characteristics: ['Indoor', 'Easy Care'],
    description: 'Aibel – Code: AIB-29',
    customisable: false,
  },
  {
    id: 30,
    name: 'Aion Polyester Rug 8x10',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2950,
    availability: false,
    size: '8x10',
    color: 'Gray',
    material: 'Polyester',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Aion',
    characteristics: ['Outdoor', 'Pet Friendly'],
    description: 'Aion – Code: AIO-30',
    customisable: false,
  },
  {
    id: 31,
    name: 'Acadia Wool Rug 6x9',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2349,
    availability: true,
    size: '6x9',
    color: 'Gray',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Acadia',
    characteristics: ['Hand Crafted', 'Indoor', 'Easy Care'],
    description: 'Acadia – Code: ACA-31',
    customisable: false,
  },
  {
    id: 32,
    name: 'Aakar Cotton Rug 5x8',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1299,
    availability: true,
    size: '5x8',
    color: 'Blue',
    material: 'Cotton',
    style: 'Lines',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Easy Care', 'Indoor'],
    description: 'Aakar – Code: AAK-32',
    customisable: false,
  },
  {
    id: 33,
    name: 'Adair Rayon Rug 4x6',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1525,
    availability: false,
    size: '4x6',
    color: 'Green',
    material: 'Rayon',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Adair',
    characteristics: ['Outdoor', 'Pet Friendly'],
    description: 'Adair – Code: ADA-33',
    customisable: false,
  },
  {
    id: 34,
    name: 'Aibel Wool Rug 3x5',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1025,
    availability: true,
    size: '3x5',
    color: 'Red',
    material: 'Wool',
    style: 'Botanical',
    pileHeight: 'High-Low',
    collection: 'Aibel',
    characteristics: ['Natural Fiber', 'Hand Crafted'],
    description: 'Aibel – Code: AIB-34',
    customisable: false,
  },
  {
    id: 35,
    name: 'Aion Linen Rug 2x3',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 699,
    availability: true,
    size: '2x3',
    color: 'Pink',
    material: 'Linen',
    style: 'Vintage',
    pileHeight: 'Low',
    collection: 'Aion',
    characteristics: ['Easy Care', 'Indoor'],
    description: 'Aion – Code: AIO-35',
    customisable: false,
  },
  {
    id: 36,
    name: 'Acadia Polyester Rug Square',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1150,
    availability: false,
    size: 'Square',
    color: 'Black',
    material: 'Polyester',
    style: 'Geometry',
    pileHeight: 'Medium',
    collection: 'Acadia',
    characteristics: ['Indoor', 'Easy Care'],
    description: 'Acadia – Code: ACA-36',
    customisable: false,
  },
  {
    id: 37,
    name: 'Aakar Cotton Rug 6x9',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1650,
    availability: true,
    size: '6x9',
    color: 'Gray',
    material: 'Cotton',
    style: 'Solid',
    pileHeight: 'Low',
    collection: 'Aakar',
    characteristics: ['Indoor', 'Hand Crafted'],
    description: 'Aakar – Code: AAK-37',
    customisable: false,
  },
  {
    id: 38,
    name: 'Adair Wool Rug Oval',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 2450,
    availability: true,
    size: 'Oval',
    color: 'Multicolor',
    material: 'Wool',
    style: 'Traditional',
    pileHeight: 'Medium',
    collection: 'Adair',
    characteristics: ['Natural Fiber', 'Indoor', 'Easy Care'],
    description: 'Adair – Code: ADA-38',
    customisable: false,
  },
  {
    id: 39,
    name: 'Aibel Rayon Rug 5x8',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1875,
    availability: false,
    size: '5x8',
    color: 'Gray',
    material: 'Rayon',
    style: 'Geometry',
    pileHeight: 'Medium',
    collection: 'Aibel',
    characteristics: ['Indoor', 'Outdoor'],
    description: 'Aibel – Code: AIB-39',
    customisable: false,
  },
  {
    id: 40,
    name: 'Aion Polyester Rug 4x6',
    image:
      'https://images.unsplash.com/photo-1588421874990-1fe162747f9b?w=800&h=1200&fit=crop',
    price: 1399,
    availability: true,
    size: '4x6',
    color: 'Gray',
    material: 'Polyester',
    style: 'Abstract',
    pileHeight: 'High',
    collection: 'Aion',
    characteristics: ['Easy Care', 'Pet Friendly'],
    description: 'Aion – Code: AIO-40',
    customisable: true,
  },
];
export default dummyData;
